# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect for the API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Define the background function with a longer timeout
[functions.tmdb-background-import]
  included_files = ["src/**", "netlify/functions/**"]
  external_node_modules = ["axios", "@supabase/supabase-js"]
  background = true
  timeout = 900 # 15 minutes in seconds
