# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Disable chunking for Radix UI compatibility
[build.processing.js]
  bundle = false

# Edge functions configuration
[functions]
  directory = "netlify/functions"

[functions."omdb-edge"]
  path = "netlify/edge-functions/omdb-edge.js"
