# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Edge functions configuration
[[edge_functions]]
  path = "/api/omdb-edge"
  function = "omdb-edge"

[[edge_functions]]
  path = "/api/test-edge"
  function = "test-edge"

# Redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
