# Netlify configuration file

[build]
  command = "npm run build-no-errors"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge functions configuration
[[edge_functions]]
  path = "/api/omdb/*"
  function = "omdb-edge"

[[edge_functions]]
  path = "/api/test"
  function = "test-edge"
