[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@tensorflow/tfjs-node"]
  # Schedule the trending content refresh function to run daily at 00:00 UTC
  included_files = []

[functions.refresh-trending]
  schedule = "0 0 * * *"

[[edge_functions]]
  path = "/api/omdb-edge/*"
  function = "omdb-edge"

[[redirects]]
  from = "/api/omdb-edge/*"
  to = "/.netlify/edge-functions/omdb-edge"
  status = 200
