[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@tensorflow/tfjs-node"]

# Schedule the trending content refresh function to run daily at 00:00 UTC
[[functions]]
  name = "refresh-trending"
  schedule = "0 0 * * *"
